//
// File generated by HDevelop for HALCON/.NET (C#) Version 24.05.0.0
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public class HDevelopExport
{
    public void dev_open_window_fit_size(HTuple hv_Row, HTuple hv_Column, HTuple hv_Width,
        HTuple hv_Height, HTuple hv_WidthLimit, HTuple hv_HeightLimit, out HTuple hv_WindowHandle, HTuple windowHandle)
    {

        HTuple hv_MinWidth = new HTuple(), hv_MaxWidth = new HTuple();
        HTuple hv_MinHeight = new HTuple(), hv_MaxHeight = new HTuple();
        HTuple hv_ResizeFactor = new HTuple(), hv_TempWidth = new HTuple();
        HTuple hv_TempHeight = new HTuple(), hv_WindowWidth = new HTuple();
        HTuple hv_WindowHeight = new HTuple();

        hv_WindowHandle = new HTuple();
        if ((int)((new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(0))).TupleOr(
            new HTuple(hv_WidthLimit.TupleLess(0)))) != 0)
        {

            hv_MinWidth.Dispose();
            hv_MinWidth = 500;
            hv_MaxWidth.Dispose();
            hv_MaxWidth = 800;
        }
        else if ((int)(new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(
            1))) != 0)
        {
            hv_MinWidth.Dispose();
            hv_MinWidth = 0;
            hv_MaxWidth.Dispose();
            hv_MaxWidth = new HTuple(hv_WidthLimit);
        }
        else
        {
            hv_MinWidth.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MinWidth = hv_WidthLimit.TupleSelect(
                    0);
            }
            hv_MaxWidth.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MaxWidth = hv_WidthLimit.TupleSelect(
                    1);
            }
        }
        //Parse input tuple HeightLimit
        if ((int)((new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(0))).TupleOr(
            new HTuple(hv_HeightLimit.TupleLess(0)))) != 0)
        {
            hv_MinHeight.Dispose();
            hv_MinHeight = 400;
            hv_MaxHeight.Dispose();
            hv_MaxHeight = 600;
        }
        else if ((int)(new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(
            1))) != 0)
        {
            hv_MinHeight.Dispose();
            hv_MinHeight = 0;
            hv_MaxHeight.Dispose();
            hv_MaxHeight = new HTuple(hv_HeightLimit);
        }
        else
        {
            hv_MinHeight.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MinHeight = hv_HeightLimit.TupleSelect(
                    0);
            }
            hv_MaxHeight.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MaxHeight = hv_HeightLimit.TupleSelect(
                    1);
            }
        }
        //
        //Test, if window size has to be changed.
        hv_ResizeFactor.Dispose();
        hv_ResizeFactor = 1;
        //First, expand window to the minimum extents (if necessary).
        if ((int)((new HTuple(hv_MinWidth.TupleGreater(hv_Width))).TupleOr(new HTuple(hv_MinHeight.TupleGreater(
            hv_Height)))) != 0)
        {
            hv_ResizeFactor.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_ResizeFactor = (((((hv_MinWidth.TupleReal()
                    ) / hv_Width)).TupleConcat((hv_MinHeight.TupleReal()) / hv_Height))).TupleMax()
                    ;
            }
        }
        hv_TempWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_TempWidth = hv_Width * hv_ResizeFactor;
        }
        hv_TempHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_TempHeight = hv_Height * hv_ResizeFactor;
        }
        //Then, shrink window to maximum extents (if necessary).
        if ((int)((new HTuple(hv_MaxWidth.TupleLess(hv_TempWidth))).TupleOr(new HTuple(hv_MaxHeight.TupleLess(
            hv_TempHeight)))) != 0)
        {
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                {
                    HTuple
                      ExpTmpLocalVar_ResizeFactor = hv_ResizeFactor * ((((((hv_MaxWidth.TupleReal()
                        ) / hv_TempWidth)).TupleConcat((hv_MaxHeight.TupleReal()) / hv_TempHeight))).TupleMin()
                        );
                    hv_ResizeFactor.Dispose();
                    hv_ResizeFactor = ExpTmpLocalVar_ResizeFactor;
                }
            }
        }
        hv_WindowWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_WindowWidth = hv_Width * hv_ResizeFactor;
        }
        hv_WindowHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_WindowHeight = hv_Height * hv_ResizeFactor;
        }
        //Resize window
        //dev_open_window(...);
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            HOperatorSet.SetPart(windowHandle, 0, 0, hv_Height - 1, hv_Width - 1);
        }

        hv_MinWidth.Dispose();
        hv_MaxWidth.Dispose();
        hv_MinHeight.Dispose();
        hv_MaxHeight.Dispose();
        hv_ResizeFactor.Dispose();
        hv_TempWidth.Dispose();
        hv_TempHeight.Dispose();
        hv_WindowWidth.Dispose();
        hv_WindowHeight.Dispose();

        return;
    }

    public void dev_open_window_fit_size(HTuple windowHandle,int startX,int startY,int endX,int endY)
    {
        HOperatorSet.SetPart(windowHandle, startY, startX, endY, endX);
    }
    // Main procedure 
    public void action(HTuple windowHandle, string imagePath)
    {

        HObject ho_Image, ho_GrayImage, ho_Regions;
        HObject ho_ConnectedRegions, ho_SelectedRegions;

        HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
        HTuple hv_WindowHandle = new HTuple(), hv_Area = new HTuple();
        HTuple hv_Row = new HTuple(), hv_Column = new HTuple();
        HTuple hv_Count = new HTuple();
        // Initialize local and output iconic variables 
        HOperatorSet.GenEmptyObj(out ho_Image);
        HOperatorSet.GenEmptyObj(out ho_GrayImage);
        HOperatorSet.GenEmptyObj(out ho_Regions);
        HOperatorSet.GenEmptyObj(out ho_ConnectedRegions);
        HOperatorSet.GenEmptyObj(out ho_SelectedRegions);
        ho_Image.Dispose();

        HOperatorSet.ReadImage(out ho_Image, imagePath);

        hv_Width.Dispose(); 
        hv_Height.Dispose();

        HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);

        hv_WindowHandle.Dispose();

        //dev_open_window_fit_size(0, 0, hv_Width, hv_Height, -1, -1, out hv_WindowHandle, windowHandle);
        dev_open_window_fit_size(windowHandle,0,0,hv_Height, hv_Width);
        HOperatorSet.DispObj(ho_Image, windowHandle);
        //将彩色图片转成灰色
        ho_GrayImage.Dispose();
        HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
        ho_Regions.Dispose();
        HOperatorSet.Threshold(ho_GrayImage, out ho_Regions, 0, 77);
        ho_ConnectedRegions.Dispose();
        HOperatorSet.Connection(ho_Regions, out ho_ConnectedRegions);
        ho_SelectedRegions.Dispose();
        HOperatorSet.SelectShape(ho_ConnectedRegions, out ho_SelectedRegions, "area",
            "and", 1783.99, 1911.36);
        //计算区域面积，以及中心点坐标
        hv_Area.Dispose(); hv_Row.Dispose(); hv_Column.Dispose();
        HOperatorSet.AreaCenter(ho_SelectedRegions, out hv_Area, out hv_Row, out hv_Column);
        //计算区域数量
        hv_Count.Dispose();
        HOperatorSet.CountObj(ho_SelectedRegions, out hv_Count);
        HOperatorSet.ClearWindow(windowHandle);
        HOperatorSet.DispObj(ho_Image, windowHandle);
        HOperatorSet.SetColor(windowHandle, "red");
        HOperatorSet.DispObj(ho_SelectedRegions, windowHandle);
        //设置光标位置
        HOperatorSet.SetTposition(windowHandle, 30, 330);
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            HOperatorSet.WriteString(windowHandle, ("螺栓数量" + hv_Count) + "个");
        }
        ho_Image.Dispose();
        ho_GrayImage.Dispose();
        ho_Regions.Dispose();
        ho_ConnectedRegions.Dispose();
        ho_SelectedRegions.Dispose();

        hv_Width.Dispose();
        hv_Height.Dispose();
        hv_WindowHandle.Dispose();
        hv_Area.Dispose();
        hv_Row.Dispose();
        hv_Column.Dispose();
        hv_Count.Dispose();

    }
}

