//
// File generated by HDevelop for HALCON/.NET (C#) Version 24.05.0.0
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public partial class HDevelopExport
{
  public HTuple hv_ExpDefaultWinHandle;

  // Procedures 
  // Chapter: Develop
  // Short Description: Open a new graphics window that preserves the aspect ratio of the given image size. 
  public void dev_open_window_fit_size (HTuple hv_Row, HTuple hv_Column, HTuple hv_Width, 
      HTuple hv_Height, HTuple hv_WidthLimit, HTuple hv_HeightLimit, out HTuple hv_WindowHandle)
  {



    // Local iconic variables 

    // Local control variables 

    HTuple hv_MinWidth = new HTuple(), hv_MaxWidth = new HTuple();
    HTuple hv_MinHeight = new HTuple(), hv_MaxHeight = new HTuple();
    HTuple hv_ResizeFactor = new HTuple(), hv_TempWidth = new HTuple();
    HTuple hv_TempHeight = new HTuple(), hv_WindowWidth = new HTuple();
    HTuple hv_WindowHeight = new HTuple();
    // Initialize local and output iconic variables 
    hv_WindowHandle = new HTuple();
    //This procedure open a new graphic window
    //such that it fits into the limits specified by WidthLimit
    //and HeightLimit, but also maintains the correct aspect ratio
    //given by Width and Height.
    //
    //If it is impossible to match the minimum and maximum extent requirements
    //at the same time (f.e. if the image is very long but narrow),
    //the maximum value gets a higher priority.
    //
    //Parse input tuple WidthLimit
    if ((int)((new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(0))).TupleOr(
        new HTuple(hv_WidthLimit.TupleLess(0)))) != 0)
    {
      hv_MinWidth.Dispose();
      hv_MinWidth = 500;
      hv_MaxWidth.Dispose();
      hv_MaxWidth = 800;
    }
    else if ((int)(new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(
        1))) != 0)
    {
      hv_MinWidth.Dispose();
      hv_MinWidth = 0;
      hv_MaxWidth.Dispose();
      hv_MaxWidth = new HTuple(hv_WidthLimit);
    }
    else
    {
      hv_MinWidth.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_MinWidth = hv_WidthLimit.TupleSelect(
          0);
      }
      hv_MaxWidth.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_MaxWidth = hv_WidthLimit.TupleSelect(
          1);
      }
    }
    //Parse input tuple HeightLimit
    if ((int)((new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(0))).TupleOr(
        new HTuple(hv_HeightLimit.TupleLess(0)))) != 0)
    {
      hv_MinHeight.Dispose();
      hv_MinHeight = 400;
      hv_MaxHeight.Dispose();
      hv_MaxHeight = 600;
    }
    else if ((int)(new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(
        1))) != 0)
    {
      hv_MinHeight.Dispose();
      hv_MinHeight = 0;
      hv_MaxHeight.Dispose();
      hv_MaxHeight = new HTuple(hv_HeightLimit);
    }
    else
    {
      hv_MinHeight.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_MinHeight = hv_HeightLimit.TupleSelect(
          0);
      }
      hv_MaxHeight.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_MaxHeight = hv_HeightLimit.TupleSelect(
          1);
      }
    }
    //
    //Test, if window size has to be changed.
    hv_ResizeFactor.Dispose();
    hv_ResizeFactor = 1;
    //First, expand window to the minimum extents (if necessary).
    if ((int)((new HTuple(hv_MinWidth.TupleGreater(hv_Width))).TupleOr(new HTuple(hv_MinHeight.TupleGreater(
        hv_Height)))) != 0)
    {
      hv_ResizeFactor.Dispose();
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      hv_ResizeFactor = (((((hv_MinWidth.TupleReal()
          )/hv_Width)).TupleConcat((hv_MinHeight.TupleReal())/hv_Height))).TupleMax()
          ;
      }
    }
    hv_TempWidth.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_TempWidth = hv_Width*hv_ResizeFactor;
    }
    hv_TempHeight.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_TempHeight = hv_Height*hv_ResizeFactor;
    }
    //Then, shrink window to maximum extents (if necessary).
    if ((int)((new HTuple(hv_MaxWidth.TupleLess(hv_TempWidth))).TupleOr(new HTuple(hv_MaxHeight.TupleLess(
        hv_TempHeight)))) != 0)
    {
      using (HDevDisposeHelper dh = new HDevDisposeHelper())
      {
      {
      HTuple 
        ExpTmpLocalVar_ResizeFactor = hv_ResizeFactor*((((((hv_MaxWidth.TupleReal()
          )/hv_TempWidth)).TupleConcat((hv_MaxHeight.TupleReal())/hv_TempHeight))).TupleMin()
          );
      hv_ResizeFactor.Dispose();
      hv_ResizeFactor = ExpTmpLocalVar_ResizeFactor;
      }
      }
    }
    hv_WindowWidth.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_WindowWidth = hv_Width*hv_ResizeFactor;
    }
    hv_WindowHeight.Dispose();
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    hv_WindowHeight = hv_Height*hv_ResizeFactor;
    }
    //Resize window
    //dev_open_window(...);
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    HOperatorSet.SetPart(hv_ExpDefaultWinHandle, 0, 0, hv_Height-1, hv_Width-1);
    }

    hv_MinWidth.Dispose();
    hv_MaxWidth.Dispose();
    hv_MinHeight.Dispose();
    hv_MaxHeight.Dispose();
    hv_ResizeFactor.Dispose();
    hv_TempWidth.Dispose();
    hv_TempHeight.Dispose();
    hv_WindowWidth.Dispose();
    hv_WindowHeight.Dispose();

    return;
  }

  // Main procedure 
  private void action()
  {


    // Local iconic variables 

    HObject ho_Image, ho_Circle, ho_Rectangle;
    HObject ho_RegionDifference, ho_ImageReduced, ho_Region;
    HObject ho_ImageRegion, ho_ImagePart, ho_Circle1, ho_ImageReduced1;
    HObject ho_ImagePart1;

    // Local control variables 

    HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
    HTuple hv_WindowHandle = new HTuple(), hv_Row = new HTuple();
    HTuple hv_Column = new HTuple(), hv_Radius = new HTuple();
    HTuple hv_Row1 = new HTuple(), hv_Column1 = new HTuple();
    HTuple hv_Row2 = new HTuple(), hv_Column2 = new HTuple();
    HTuple hv_DrawID = new HTuple(), hv_ParamValues = new HTuple();
    // Initialize local and output iconic variables 
    HOperatorSet.GenEmptyObj(out ho_Image);
    HOperatorSet.GenEmptyObj(out ho_Circle);
    HOperatorSet.GenEmptyObj(out ho_Rectangle);
    HOperatorSet.GenEmptyObj(out ho_RegionDifference);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced);
    HOperatorSet.GenEmptyObj(out ho_Region);
    HOperatorSet.GenEmptyObj(out ho_ImageRegion);
    HOperatorSet.GenEmptyObj(out ho_ImagePart);
    HOperatorSet.GenEmptyObj(out ho_Circle1);
    HOperatorSet.GenEmptyObj(out ho_ImageReduced1);
    HOperatorSet.GenEmptyObj(out ho_ImagePart1);
    ho_Image.Dispose();
    HOperatorSet.ReadImage(out ho_Image, "G:/Code/githubCode/csharp-note/Halcon素材/Floppies.jpg");
    hv_Width.Dispose();hv_Height.Dispose();
    HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);
    //dev_close_window(...);
    hv_WindowHandle.Dispose();
    dev_open_window_fit_size(0, 0, hv_Width, hv_Height, -1, -1, out hv_WindowHandle);
    HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);

    HOperatorSet.SetColor(hv_ExpDefaultWinHandle, "red");
    HOperatorSet.SetDraw(hv_ExpDefaultWinHandle, "margin");
    //* 绘制不感兴趣区域
    hv_Row.Dispose();hv_Column.Dispose();hv_Radius.Dispose();
    HOperatorSet.DrawCircle(hv_ExpDefaultWinHandle, out hv_Row, out hv_Column, out hv_Radius);
    ho_Circle.Dispose();
    HOperatorSet.GenCircle(out ho_Circle, hv_Row, hv_Column, hv_Radius);

    hv_Row1.Dispose();hv_Column1.Dispose();hv_Row2.Dispose();hv_Column2.Dispose();
    HOperatorSet.DrawRectangle1(hv_ExpDefaultWinHandle, out hv_Row1, out hv_Column1, 
        out hv_Row2, out hv_Column2);
    ho_Rectangle.Dispose();
    HOperatorSet.GenRectangle1(out ho_Rectangle, hv_Row1, hv_Column1, hv_Row2, hv_Column2);
    //求两个区域差
    ho_RegionDifference.Dispose();
    HOperatorSet.Difference(ho_Circle, ho_Rectangle, out ho_RegionDifference);
    ho_ImageReduced.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_RegionDifference, out ho_ImageReduced);
    HOperatorSet.ClearWindow(hv_ExpDefaultWinHandle);
    HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);

    //绘制任意区域
    ho_Region.Dispose();
    HOperatorSet.DrawRegion(out ho_Region, hv_ExpDefaultWinHandle);

    ho_ImageRegion.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_Region, out ho_ImageRegion);

    ho_ImagePart.Dispose();
    HOperatorSet.CropDomain(ho_ImageRegion, out ho_ImagePart);
    HOperatorSet.WriteImage(ho_ImagePart, "png", 0, "roi_region");

    //使用缩放工具绘制区域
    //创建一个可拉伸的圆形
    hv_DrawID.Dispose();
    HOperatorSet.CreateDrawingObjectCircle(hv_Row, hv_Column, hv_Radius, out hv_DrawID);
    //将所创建的圆形放到窗体上显示出来
    HOperatorSet.AttachDrawingObjectToWindow(hv_ExpDefaultWinHandle, hv_DrawID);
    HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
    //获取创建对象的参数
    hv_ParamValues.Dispose();
    HOperatorSet.GetDrawingObjectParams(hv_DrawID, ((new HTuple("row")).TupleConcat(
        "column")).TupleConcat("radius"), out hv_ParamValues);
    //根据返回的参数将它绘制出来
    using (HDevDisposeHelper dh = new HDevDisposeHelper())
    {
    ho_Circle1.Dispose();
    HOperatorSet.GenCircle(out ho_Circle1, hv_ParamValues.TupleSelect(0), hv_ParamValues.TupleSelect(
        1), hv_ParamValues.TupleSelect(2));
    }
    ho_ImageReduced1.Dispose();
    HOperatorSet.ReduceDomain(ho_Image, ho_Circle1, out ho_ImageReduced1);
    ho_ImagePart1.Dispose();
    HOperatorSet.CropDomain(ho_ImageReduced1, out ho_ImagePart1);
    HOperatorSet.WriteImage(ho_ImagePart1, "png", 0, "draw_object");
    //将创建的对象从窗体上删除
    HOperatorSet.DetachDrawingObjectFromWindow(hv_ExpDefaultWinHandle, hv_DrawID);

    ho_Image.Dispose();
    ho_Circle.Dispose();
    ho_Rectangle.Dispose();
    ho_RegionDifference.Dispose();
    ho_ImageReduced.Dispose();
    ho_Region.Dispose();
    ho_ImageRegion.Dispose();
    ho_ImagePart.Dispose();
    ho_Circle1.Dispose();
    ho_ImageReduced1.Dispose();
    ho_ImagePart1.Dispose();

    hv_Width.Dispose();
    hv_Height.Dispose();
    hv_WindowHandle.Dispose();
    hv_Row.Dispose();
    hv_Column.Dispose();
    hv_Radius.Dispose();
    hv_Row1.Dispose();
    hv_Column1.Dispose();
    hv_Row2.Dispose();
    hv_Column2.Dispose();
    hv_DrawID.Dispose();
    hv_ParamValues.Dispose();

  }

  public void InitHalcon()
  {
    // Default settings used in HDevelop
    HOperatorSet.SetSystem("width", 512);
    HOperatorSet.SetSystem("height", 512);
  }

  public void RunHalcon(HTuple Window)
  {
    hv_ExpDefaultWinHandle = Window;
    action();
  }

}

