//
// File generated by HDevelop for HALCON/.NET (C#) Version 25.05.0.0
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using System.Windows.Forms;
using HalconDotNet;

public class HDevelopExport
{
    public HTuple hv_ExpDefaultWinHandle;

    public void HDevelopStop()
    {
        MessageBox.Show("Press button to continue", "Program stop");
    }

    // Procedures 
    // Chapter: Develop
    // Short Description: Open a new graphics window that preserves the aspect ratio of the given image size. 
    public void dev_open_window_fit_size(HTuple hv_Row, HTuple hv_Column, HTuple hv_Width,
        HTuple hv_Height, HTuple hv_WidthLimit, HTuple hv_HeightLimit, out HTuple hv_WindowHandle)
    {

        // Local iconic variables 

        // Local control variables 

        HTuple hv_MinWidth = new HTuple(), hv_MaxWidth = new HTuple();
        HTuple hv_MinHeight = new HTuple(), hv_MaxHeight = new HTuple();
        HTuple hv_ResizeFactor = new HTuple(), hv_TempWidth = new HTuple();
        HTuple hv_TempHeight = new HTuple(), hv_WindowWidth = new HTuple();
        HTuple hv_WindowHeight = new HTuple();
        // Initialize local and output iconic variables 
        hv_WindowHandle = new HTuple();
        //This procedure open a new graphic window
        //such that it fits into the limits specified by WidthLimit
        //and HeightLimit, but also maintains the correct aspect ratio
        //given by Width and Height.
        //
        //If it is impossible to match the minimum and maximum extent requirements
        //at the same time (f.e. if the image is very long but narrow),
        //the maximum value gets a higher priority.
        //
        //Parse input tuple WidthLimit
        if ((int)((new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(0))).TupleOr(
            new HTuple(hv_WidthLimit.TupleLess(0)))) != 0)
        {
            hv_MinWidth.Dispose();
            hv_MinWidth = 500;
            hv_MaxWidth.Dispose();
            hv_MaxWidth = 800;
        }
        else if ((int)(new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(
            1))) != 0)
        {
            hv_MinWidth.Dispose();
            hv_MinWidth = 0;
            hv_MaxWidth.Dispose();
            hv_MaxWidth = new HTuple(hv_WidthLimit);
        }
        else
        {
            hv_MinWidth.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MinWidth = hv_WidthLimit.TupleSelect(
                    0);
            }
            hv_MaxWidth.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MaxWidth = hv_WidthLimit.TupleSelect(
                    1);
            }
        }
        //Parse input tuple HeightLimit
        if ((int)((new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(0))).TupleOr(
            new HTuple(hv_HeightLimit.TupleLess(0)))) != 0)
        {
            hv_MinHeight.Dispose();
            hv_MinHeight = 400;
            hv_MaxHeight.Dispose();
            hv_MaxHeight = 600;
        }
        else if ((int)(new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(
            1))) != 0)
        {
            hv_MinHeight.Dispose();
            hv_MinHeight = 0;
            hv_MaxHeight.Dispose();
            hv_MaxHeight = new HTuple(hv_HeightLimit);
        }
        else
        {
            hv_MinHeight.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MinHeight = hv_HeightLimit.TupleSelect(
                    0);
            }
            hv_MaxHeight.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MaxHeight = hv_HeightLimit.TupleSelect(
                    1);
            }
        }
        //
        //Test, if window size has to be changed.
        hv_ResizeFactor.Dispose();
        hv_ResizeFactor = 1;
        //First, expand window to the minimum extents (if necessary).
        if ((int)((new HTuple(hv_MinWidth.TupleGreater(hv_Width))).TupleOr(new HTuple(hv_MinHeight.TupleGreater(
            hv_Height)))) != 0)
        {
            hv_ResizeFactor.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_ResizeFactor = (((((hv_MinWidth.TupleReal()
                    ) / hv_Width)).TupleConcat((hv_MinHeight.TupleReal()) / hv_Height))).TupleMax()
                    ;
            }
        }
        hv_TempWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_TempWidth = hv_Width * hv_ResizeFactor;
        }
        hv_TempHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_TempHeight = hv_Height * hv_ResizeFactor;
        }
        //Then, shrink window to maximum extents (if necessary).
        if ((int)((new HTuple(hv_MaxWidth.TupleLess(hv_TempWidth))).TupleOr(new HTuple(hv_MaxHeight.TupleLess(
            hv_TempHeight)))) != 0)
        {
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                {
                    HTuple
                      ExpTmpLocalVar_ResizeFactor = hv_ResizeFactor * ((((((hv_MaxWidth.TupleReal()
                        ) / hv_TempWidth)).TupleConcat((hv_MaxHeight.TupleReal()) / hv_TempHeight))).TupleMin()
                        );
                    hv_ResizeFactor.Dispose();
                    hv_ResizeFactor = ExpTmpLocalVar_ResizeFactor;
                }
            }
        }
        hv_WindowWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_WindowWidth = hv_Width * hv_ResizeFactor;
        }
        hv_WindowHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_WindowHeight = hv_Height * hv_ResizeFactor;
        }
        //Resize window
        //dev_open_window(...);
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            HOperatorSet.SetPart(hv_ExpDefaultWinHandle, 0, 0, hv_Height - 1, hv_Width - 1);
        }

        hv_MinWidth.Dispose();
        hv_MaxWidth.Dispose();
        hv_MinHeight.Dispose();
        hv_MaxHeight.Dispose();
        hv_ResizeFactor.Dispose();
        hv_TempWidth.Dispose();
        hv_TempHeight.Dispose();
        hv_WindowWidth.Dispose();
        hv_WindowHeight.Dispose();

        return;
    }

    // Main procedure 
    private void action()
    {


        // Local iconic variables 

        HObject ho_Image, ho_GrayImage, ho_Circle;
        HObject ho_ImageReduced, ho_Region, ho_RegionDilation, ho_Contours;
        HObject ho_Circle1, ho_RegionAffineTrans = null, ho_Cross = null;
        HObject ho_Cross2 = null;

        // Local control variables 

        HTuple hv_Channels = new HTuple(), hv_Width = new HTuple();
        HTuple hv_Height = new HTuple(), hv_WindowHandle = new HTuple();
        HTuple hv_Row1 = new HTuple(), hv_Column1 = new HTuple();
        HTuple hv_Radius = new HTuple(), hv_Area = new HTuple();
        HTuple hv_CenterY = new HTuple(), hv_CenterX = new HTuple();
        HTuple hv_ModelID = new HTuple(), hv_Row2 = new HTuple();
        HTuple hv_Column2 = new HTuple(), hv_Radius1 = new HTuple();
        HTuple hv_StartPhi = new HTuple(), hv_EndPhi = new HTuple();
        HTuple hv_PointOrder = new HTuple(), hv_Rows = new HTuple();
        HTuple hv_Columns = new HTuple(), hv_Row = new HTuple();
        HTuple hv_Column = new HTuple(), hv_Angle = new HTuple();
        HTuple hv_Score = new HTuple(), hv_Index = new HTuple();
        HTuple hv_HomMat2D = new HTuple();
        // Initialize local and output iconic variables 
        HOperatorSet.GenEmptyObj(out ho_Image);
        HOperatorSet.GenEmptyObj(out ho_GrayImage);
        HOperatorSet.GenEmptyObj(out ho_Circle);
        HOperatorSet.GenEmptyObj(out ho_ImageReduced);
        HOperatorSet.GenEmptyObj(out ho_Region);
        HOperatorSet.GenEmptyObj(out ho_RegionDilation);
        HOperatorSet.GenEmptyObj(out ho_Contours);
        HOperatorSet.GenEmptyObj(out ho_Circle1);
        HOperatorSet.GenEmptyObj(out ho_RegionAffineTrans);
        HOperatorSet.GenEmptyObj(out ho_Cross);
        HOperatorSet.GenEmptyObj(out ho_Cross2);
        ho_Image.Dispose();
        HOperatorSet.ReadImage(out ho_Image, "E:/资料/给网课学员类库及资料作业/华山培训视觉修正坐标类库/圆点.jpg");
        ho_GrayImage.Dispose();
        HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
        hv_Channels.Dispose();
        HOperatorSet.CountChannels(ho_GrayImage, out hv_Channels);
        hv_Width.Dispose(); hv_Height.Dispose();
        HOperatorSet.GetImageSize(ho_GrayImage, out hv_Width, out hv_Height);
        //dev_close_window(...);
        hv_WindowHandle.Dispose();
        dev_open_window_fit_size(0, 0, hv_Width, hv_Height, -1, -1, out hv_WindowHandle);
        //控制程序执行期间是否自动将图形输出对象（如图像、区域、轮廓）显示在活动的图形窗口中
        // dev_update_window(...); only in hdevelop
        HOperatorSet.SetDraw(hv_ExpDefaultWinHandle, "margin");
        HOperatorSet.DispObj(ho_GrayImage, hv_ExpDefaultWinHandle);

        hv_Row1.Dispose(); hv_Column1.Dispose(); hv_Radius.Dispose();
        HOperatorSet.DrawCircle(hv_ExpDefaultWinHandle, out hv_Row1, out hv_Column1,
            out hv_Radius);
        ho_Circle.Dispose();
        HOperatorSet.GenCircle(out ho_Circle, hv_Row1, hv_Column1, hv_Radius);
        //计算输入区域的面积和中心坐标
        hv_Area.Dispose(); hv_CenterY.Dispose(); hv_CenterX.Dispose();
        HOperatorSet.AreaCenter(ho_Circle, out hv_Area, out hv_CenterY, out hv_CenterX);
        //保留感兴趣区域
        ho_ImageReduced.Dispose();
        HOperatorSet.ReduceDomain(ho_GrayImage, ho_Circle, out ho_ImageReduced);
        //创建用于匹配的NCC模型
        hv_ModelID.Dispose();
        HOperatorSet.CreateNccModel(ho_ImageReduced, "auto", 0, 0, "auto", "use_polarity",
            out hv_ModelID);
        ho_Region.Dispose();
        HOperatorSet.Threshold(ho_ImageReduced, out ho_Region, 0, 100);
        //对圆进行膨胀
        ho_RegionDilation.Dispose();
        HOperatorSet.DilationCircle(ho_Region, out ho_RegionDilation, 5.5);
        //将区域转成轮廓对象
        ho_Contours.Dispose();
        HOperatorSet.GenContourRegionXld(ho_Region, out ho_Contours, "border");
        //通过圆逼近输入的轮廓，生成一个圆
        hv_Row2.Dispose(); hv_Column2.Dispose(); hv_Radius1.Dispose(); hv_StartPhi.Dispose(); hv_EndPhi.Dispose(); hv_PointOrder.Dispose();
        HOperatorSet.FitCircleContourXld(ho_Contours, "algebraic", -1, 0, 0, 3, 2, out hv_Row2,
            out hv_Column2, out hv_Radius1, out hv_StartPhi, out hv_EndPhi, out hv_PointOrder);
        HOperatorSet.ClearWindow(hv_ExpDefaultWinHandle);
        HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
        ho_Circle1.Dispose();
        HOperatorSet.GenCircle(out ho_Circle1, hv_Row2, hv_Column2, hv_Radius1);
        HOperatorSet.DispObj(ho_Circle, hv_ExpDefaultWinHandle);
        hv_Rows.Dispose();
        hv_Rows = new HTuple();
        hv_Columns.Dispose();
        hv_Columns = new HTuple();

        hv_Row.Dispose(); hv_Column.Dispose(); hv_Angle.Dispose(); hv_Score.Dispose();
        HOperatorSet.FindNccModel(ho_GrayImage, hv_ModelID, 0, 0, 0.5, 5, 0.5, "true",
            (new HTuple(4)).TupleConcat(1), out hv_Row, out hv_Column, out hv_Angle,
            out hv_Score);

        // dev_update_window(...); only in hdevelop
        for (hv_Index = 0; (int)hv_Index <= (int)((new HTuple(hv_Score.TupleLength())) - 1); hv_Index = (int)hv_Index + 1)
        {
            //计算一个从模板中心到匹配点的刚体变换矩阵HomMat2D，该变换包括平移和旋转
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_HomMat2D.Dispose();
                HOperatorSet.VectorAngleToRigid(hv_CenterY, hv_CenterX, 0, hv_Row.TupleSelect(
                    hv_Index), hv_Column.TupleSelect(hv_Index), 0, out hv_HomMat2D);
            }
            //将原始的圆形模板区域应用上述变换，使其与图像中匹配目标的位置和方向对齐
            ho_RegionAffineTrans.Dispose();
            HOperatorSet.AffineTransRegion(ho_ImageReduced, out ho_RegionAffineTrans, hv_HomMat2D,
                "nearest_neighbor");
            HOperatorSet.DispObj(ho_RegionAffineTrans, hv_ExpDefaultWinHandle);
            //在匹配中心点生成一个十字形轮廓标记，其方向与匹配角度一致
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                ho_Cross.Dispose();
                HOperatorSet.GenCrossContourXld(out ho_Cross, hv_Row.TupleSelect(hv_Index),
                    hv_Column.TupleSelect(hv_Index), 12, hv_Angle.TupleSelect(hv_Index));
            }
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                ho_Cross2.Dispose();
                HOperatorSet.GenCrossContourXld(out ho_Cross2, hv_Row2, hv_Column2, 6, hv_Angle.TupleSelect(
                    hv_Index));
            }

        }
        HDevelopStop();
        HOperatorSet.ClearNccModel(hv_ModelID);
        ho_Image.Dispose();
        ho_GrayImage.Dispose();
        ho_Circle.Dispose();
        ho_ImageReduced.Dispose();
        ho_Region.Dispose();
        ho_RegionDilation.Dispose();
        ho_Contours.Dispose();
        ho_Circle1.Dispose();
        ho_RegionAffineTrans.Dispose();
        ho_Cross.Dispose();
        ho_Cross2.Dispose();

        hv_Channels.Dispose();
        hv_Width.Dispose();
        hv_Height.Dispose();
        hv_WindowHandle.Dispose();
        hv_Row1.Dispose();
        hv_Column1.Dispose();
        hv_Radius.Dispose();
        hv_Area.Dispose();
        hv_CenterY.Dispose();
        hv_CenterX.Dispose();
        hv_ModelID.Dispose();
        hv_Row2.Dispose();
        hv_Column2.Dispose();
        hv_Radius1.Dispose();
        hv_StartPhi.Dispose();
        hv_EndPhi.Dispose();
        hv_PointOrder.Dispose();
        hv_Rows.Dispose();
        hv_Columns.Dispose();
        hv_Row.Dispose();
        hv_Column.Dispose();
        hv_Angle.Dispose();
        hv_Score.Dispose();
        hv_Index.Dispose();
        hv_HomMat2D.Dispose();

    }

    public void InitHalcon()
    {
        // Default settings used in HDevelop
        HOperatorSet.SetSystem("width", 512);
        HOperatorSet.SetSystem("height", 512);
    }

    public void RunHalcon(HTuple Window)
    {
        hv_ExpDefaultWinHandle = Window;
        action();
    }

}

