//
// File generated by HDevelop for HALCON/.NET (C#) Version 25.05.0.0
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using HalconDotNet;

public class ShapeModelMatch
{
    public HTuple hv_ExpDefaultWinHandle;

    // Procedures 
    // Chapter: Develop
    // Short Description: Open a new graphics window that preserves the aspect ratio of the given image size. 
    public void dev_open_window_fit_size(HTuple hv_Row, HTuple hv_Column, HTuple hv_Width,
        HTuple hv_Height, HTuple hv_WidthLimit, HTuple hv_HeightLimit, out HTuple hv_WindowHandle)
    {



        // Local iconic variables 

        // Local control variables 

        HTuple hv_MinWidth = new HTuple(), hv_MaxWidth = new HTuple();
        HTuple hv_MinHeight = new HTuple(), hv_MaxHeight = new HTuple();
        HTuple hv_ResizeFactor = new HTuple(), hv_TempWidth = new HTuple();
        HTuple hv_TempHeight = new HTuple(), hv_WindowWidth = new HTuple();
        HTuple hv_WindowHeight = new HTuple();
        // Initialize local and output iconic variables 
        hv_WindowHandle = new HTuple();
        //This procedure open a new graphic window
        //such that it fits into the limits specified by WidthLimit
        //and HeightLimit, but also maintains the correct aspect ratio
        //given by Width and Height.
        //
        //If it is impossible to match the minimum and maximum extent requirements
        //at the same time (f.e. if the image is very long but narrow),
        //the maximum value gets a higher priority.
        //
        //Parse input tuple WidthLimit
        if ((int)((new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(0))).TupleOr(
            new HTuple(hv_WidthLimit.TupleLess(0)))) != 0)
        {
            hv_MinWidth.Dispose();
            hv_MinWidth = 500;
            hv_MaxWidth.Dispose();
            hv_MaxWidth = 800;
        }
        else if ((int)(new HTuple((new HTuple(hv_WidthLimit.TupleLength())).TupleEqual(
            1))) != 0)
        {
            hv_MinWidth.Dispose();
            hv_MinWidth = 0;
            hv_MaxWidth.Dispose();
            hv_MaxWidth = new HTuple(hv_WidthLimit);
        }
        else
        {
            hv_MinWidth.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MinWidth = hv_WidthLimit.TupleSelect(
                    0);
            }
            hv_MaxWidth.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MaxWidth = hv_WidthLimit.TupleSelect(
                    1);
            }
        }
        //Parse input tuple HeightLimit
        if ((int)((new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(0))).TupleOr(
            new HTuple(hv_HeightLimit.TupleLess(0)))) != 0)
        {
            hv_MinHeight.Dispose();
            hv_MinHeight = 400;
            hv_MaxHeight.Dispose();
            hv_MaxHeight = 600;
        }
        else if ((int)(new HTuple((new HTuple(hv_HeightLimit.TupleLength())).TupleEqual(
            1))) != 0)
        {
            hv_MinHeight.Dispose();
            hv_MinHeight = 0;
            hv_MaxHeight.Dispose();
            hv_MaxHeight = new HTuple(hv_HeightLimit);
        }
        else
        {
            hv_MinHeight.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MinHeight = hv_HeightLimit.TupleSelect(
                    0);
            }
            hv_MaxHeight.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_MaxHeight = hv_HeightLimit.TupleSelect(
                    1);
            }
        }
        //
        //Test, if window size has to be changed.
        hv_ResizeFactor.Dispose();
        hv_ResizeFactor = 1;
        //First, expand window to the minimum extents (if necessary).
        if ((int)((new HTuple(hv_MinWidth.TupleGreater(hv_Width))).TupleOr(new HTuple(hv_MinHeight.TupleGreater(
            hv_Height)))) != 0)
        {
            hv_ResizeFactor.Dispose();
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                hv_ResizeFactor = (((((hv_MinWidth.TupleReal()
                    ) / hv_Width)).TupleConcat((hv_MinHeight.TupleReal()) / hv_Height))).TupleMax()
                    ;
            }
        }
        hv_TempWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_TempWidth = hv_Width * hv_ResizeFactor;
        }
        hv_TempHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_TempHeight = hv_Height * hv_ResizeFactor;
        }
        //Then, shrink window to maximum extents (if necessary).
        if ((int)((new HTuple(hv_MaxWidth.TupleLess(hv_TempWidth))).TupleOr(new HTuple(hv_MaxHeight.TupleLess(
            hv_TempHeight)))) != 0)
        {
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                {
                    HTuple
                      ExpTmpLocalVar_ResizeFactor = hv_ResizeFactor * ((((((hv_MaxWidth.TupleReal()
                        ) / hv_TempWidth)).TupleConcat((hv_MaxHeight.TupleReal()) / hv_TempHeight))).TupleMin()
                        );
                    hv_ResizeFactor.Dispose();
                    hv_ResizeFactor = ExpTmpLocalVar_ResizeFactor;
                }
            }
        }
        hv_WindowWidth.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_WindowWidth = hv_Width * hv_ResizeFactor;
        }
        hv_WindowHeight.Dispose();
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_WindowHeight = hv_Height * hv_ResizeFactor;
        }
        //Resize window
        //dev_open_window(...);
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            HOperatorSet.SetPart(hv_ExpDefaultWinHandle, 0, 0, hv_Height - 1, hv_Width - 1);
        }

        hv_MinWidth.Dispose();
        hv_MaxWidth.Dispose();
        hv_MinHeight.Dispose();
        hv_MaxHeight.Dispose();
        hv_ResizeFactor.Dispose();
        hv_TempWidth.Dispose();
        hv_TempHeight.Dispose();
        hv_WindowWidth.Dispose();
        hv_WindowHeight.Dispose();

        return;
    }

    // Main procedure 
    private void action()
    {


        // Local iconic variables 

        HObject ho_Image, ho_ModelRegion, ho_TemplateImage;
        HObject ho_ModelContours, ho_ContoursAffineTrans = null;

        // Local control variables 

        HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
        HTuple hv_WindowHandle = new HTuple(), hv_ModelID = new HTuple();
        HTuple hv_Row = new HTuple(), hv_Column = new HTuple();
        HTuple hv_Angle = new HTuple(), hv_ModelScore = new HTuple();
        HTuple hv_index = new HTuple(), hv_HomMat = new HTuple();
        // Initialize local and output iconic variables 
        HOperatorSet.GenEmptyObj(out ho_Image);
        HOperatorSet.GenEmptyObj(out ho_ModelRegion);
        HOperatorSet.GenEmptyObj(out ho_TemplateImage);
        HOperatorSet.GenEmptyObj(out ho_ModelContours);
        HOperatorSet.GenEmptyObj(out ho_ContoursAffineTrans);

        //Matching 01: Obtain the model image
        ho_Image.Dispose();
        HOperatorSet.ReadImage(out ho_Image, "../Halcon素材/Floppies.jpg");
        //dev_close_window(...);
        hv_Width.Dispose(); hv_Height.Dispose();
        HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);
        hv_WindowHandle.Dispose();
        dev_open_window_fit_size(0, 0, hv_Width, hv_Height, -1, -1, out hv_WindowHandle);
        HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
        //
        //Matching 01: Build the ROI from basic regions
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            ho_ModelRegion.Dispose();
            HOperatorSet.GenRectangle2(out ho_ModelRegion, 158.807, 298.374, (new HTuple(145.487)).TupleRad()
                , 16.1506, 14.1379);
        }
        //
        //Matching 01: Reduce the model template
        ho_TemplateImage.Dispose();
        HOperatorSet.ReduceDomain(ho_Image, ho_ModelRegion, out ho_TemplateImage);

        //创建形状模型，返回它的句柄
        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_ModelID.Dispose();
            HOperatorSet.CreateShapeModel(ho_TemplateImage, 2, (new HTuple(0)).TupleRad()
                , (new HTuple(360)).TupleRad(), (new HTuple(7.04)).TupleRad(), (new HTuple("none")).TupleConcat(
                "no_pregeneration"), "use_polarity", ((new HTuple(54)).TupleConcat(86)).TupleConcat(
                6), 6, out hv_ModelID);
        }

        using (HDevDisposeHelper dh = new HDevDisposeHelper())
        {
            hv_Row.Dispose(); hv_Column.Dispose(); hv_Angle.Dispose(); hv_ModelScore.Dispose();
            HOperatorSet.FindShapeModel(ho_Image, hv_ModelID, (new HTuple(0)).TupleRad(),
                (new HTuple(360)).TupleRad(), 0.79, 5, 0.5, "least_squares", (new HTuple(2)).TupleConcat(
                1), 0.9, out hv_Row, out hv_Column, out hv_Angle, out hv_ModelScore);
        }
        //从形状模型句柄中提取轮廓
        ho_ModelContours.Dispose();
        HOperatorSet.GetShapeModelContours(out ho_ModelContours, hv_ModelID, 1);

        for (hv_index = 0; (int)hv_index <= (int)((new HTuple(hv_ModelScore.TupleLength()
            )) - 1); hv_index = (int)hv_index + 1)
        {
            //定义一个仿射变换矩阵
            hv_HomMat.Dispose();
            HOperatorSet.HomMat2dIdentity(out hv_HomMat);
            //旋转矩阵
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                HTuple ExpTmpOutVar_0;
                HOperatorSet.HomMat2dRotate(hv_HomMat, hv_Angle.TupleSelect(hv_index), 0, 0,
                    out ExpTmpOutVar_0);
                hv_HomMat.Dispose();
                hv_HomMat = ExpTmpOutVar_0;
            }
            //平移
            using (HDevDisposeHelper dh = new HDevDisposeHelper())
            {
                HTuple ExpTmpOutVar_0;
                HOperatorSet.HomMat2dTranslate(hv_HomMat, hv_Row.TupleSelect(hv_index), hv_Column.TupleSelect(
                    hv_index), out ExpTmpOutVar_0);
                hv_HomMat.Dispose();
                hv_HomMat = ExpTmpOutVar_0;
            }
            //使用构建好的变换矩阵，实际计算模板轮廓的新坐标
            ho_ContoursAffineTrans.Dispose();
            HOperatorSet.AffineTransContourXld(ho_ModelContours, out ho_ContoursAffineTrans,
                hv_HomMat);

        }
        //关闭句柄
        HOperatorSet.ClearShapeModel(hv_ModelID);
        ho_Image.Dispose();
        ho_ModelRegion.Dispose();
        ho_TemplateImage.Dispose();
        ho_ModelContours.Dispose();
        ho_ContoursAffineTrans.Dispose();

        hv_Width.Dispose();
        hv_Height.Dispose();
        hv_WindowHandle.Dispose();
        hv_ModelID.Dispose();
        hv_Row.Dispose();
        hv_Column.Dispose();
        hv_Angle.Dispose();
        hv_ModelScore.Dispose();
        hv_index.Dispose();
        hv_HomMat.Dispose();

    }

    public void InitHalcon()
    {
        // Default settings used in HDevelop
        HOperatorSet.SetSystem("width", 512);
        HOperatorSet.SetSystem("height", 512);
    }

    public void RunHalcon(HTuple Window)
    {
        hv_ExpDefaultWinHandle = Window;
        action();
    }

}

